sudo: false
dist: trusty
language: node_js

node_js:
- '7.8.0'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g typescript@2.0

script:
- karma start karma.conf.js --single-run
