/**
 * LOC-DB Central Component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Identifier } from './identifier';
import { OCRData } from './oCRData';


export interface BibliographicEntry {
    _id?: string;
    identifiers?: Array<Identifier>;
    bibliographicEntryText?: string;
    references?: string;
    scanId?: string;
    status?: string;
    ocrData?: OCRData;
}
