/**
 * LOC-DB Central Component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentRole } from './agentRole';
import { BibliographicEntry } from './bibliographicEntry';
import { Identifier } from './identifier';
import { ResourceEmbodiment } from './resourceEmbodiment';


export interface BibliographicResourceOpenCitations {
    _id?: string;
    identifiers?: Array<Identifier>;
    type?: string;
    title?: string;
    subtitle?: string;
    edition?: string;
    number?: string;
    contributors?: Array<AgentRole>;
    publicationDate?: string;
    cites?: Array<string>;
    partOf?: string;
    parts?: Array<BibliographicEntry>;
    embodiedAs?: Array<ResourceEmbodiment>;
}
