/**
 * LOC-DB Central Component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeedEntryImage } from './feedEntryImage';


export interface FeedEntryMeta {
    title?: string;
    description?: string;
    link?: string;
    xmlurl?: string;
    date?: string;
    pubdate?: string;
    author?: string;
    language?: string;
    image?: FeedEntryImage;
    favicon?: string;
    copyright?: string;
    generator?: string;
    categories?: Array<string>;
}
