/**
 * LOC-DB Central Component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OCRData {
    coordinates?: string;
    authors?: Array<string>;
    title?: string;
    date?: string;
    marker?: string;
    comments?: string;
    journal?: string;
    volume?: string;
    namer?: string;
    detector?: string;
}
