/**
 * LOC-DB Central Component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BibliographicResource {
    id?: string;

    journalIdentifiers?: Array<models.Identifier>;

    journalVolumeIdentifiers?: Array<models.Identifier>;

    journalIssueIdentifiers?: Array<models.Identifier>;

    journalArticleIdentifiers?: Array<models.Identifier>;

    monographIdentifiers?: Array<models.Identifier>;

    editedBookIdentifiers?: Array<models.Identifier>;

    bookSeriesIdentifiers?: Array<models.Identifier>;

    bookSetIdentifiers?: Array<models.Identifier>;

    bookChapterIdentifiers?: Array<models.Identifier>;

    bookSectionIdentifiers?: Array<models.Identifier>;

    bookPartIdentifiers?: Array<models.Identifier>;

    bookTrackIdentifiers?: Array<models.Identifier>;

    componentIdentifiers?: Array<models.Identifier>;

    dissertationIdentifiers?: Array<models.Identifier>;

    proceedingsArticleIdentifiers?: Array<models.Identifier>;

    proceedingsIdentifiers?: Array<models.Identifier>;

    datasetIdentifiers?: Array<models.Identifier>;

    reportIdentifiers?: Array<models.Identifier>;

    reportSeriesIdentifiers?: Array<models.Identifier>;

    bookIdentifiers?: Array<models.Identifier>;

    referenceBookIdentifiers?: Array<models.Identifier>;

    referenceEntryIdentifiers?: Array<models.Identifier>;

    standardIdentifiers?: Array<models.Identifier>;

    standardSeriesIdentifiers?: Array<models.Identifier>;

    type?: string;

    journalTitle?: string;

    journalVolumeTitle?: string;

    journalIssueTitle?: string;

    journalArticleTitle?: string;

    monographTitle?: string;

    editedBookTitle?: string;

    bookSeriesTitle?: string;

    bookSetTitle?: string;

    bookChapterTitle?: string;

    bookSectionTitle?: string;

    bookPartTitle?: string;

    bookTrackTitle?: string;

    componentTitle?: string;

    reportTitle?: string;

    proceedingsArticleTitle?: string;

    proceedingsTitle?: string;

    datasetTitle?: string;

    reportSeriesTitle?: string;

    bookTitle?: string;

    referenceBookTitle?: string;

    referenceEntryTitle?: string;

    standardTitle?: string;

    standardSeriesTitle?: string;

    editedBookSubtitle?: string;

    reportSubtitle?: string;

    dissertationSubtitle?: string;

    proceedingsArticleSubtitle?: string;

    standardSubtitle?: string;

    standardSeriesSubtitle?: string;

    journalSubtitle?: string;

    journalArticleSubtitle?: string;

    bookSeriesSubtitle?: string;

    monographSubtitle?: string;

    bookSetSubtitle?: string;

    bookPartSubtitle?: string;

    bookChapterSubtitle?: string;

    bookSectionSubtitle?: string;

    bookTrackSubtitle?: string;

    componentSubtitle?: string;

    proceedingsSubtitle?: string;

    deatasetSubtitle?: string;

    reportSeriesSubtitle?: string;

    bookSubtitle?: string;

    referenceBookSubtitle?: string;

    referenceEntrySubtitle?: string;

    monographEdition?: string;

    editedBookEdition?: string;

    dissertationEdition?: string;

    proceedingsEdition?: string;

    reportEdition?: string;

    bookEdition?: string;

    referenceBookEdition?: string;

    standardEdition?: string;

    journalVolumeNumber?: string;

    journalIssueNumber?: string;

    bookPartNumber?: string;

    monographNumber?: string;

    editedBookNumber?: string;

    componentNumber?: string;

    bookSetNumber?: string;

    bookChapterNumber?: string;

    bookSectionNumber?: string;

    bookTrackNumber?: string;

    proceedingsNumber?: string;

    reportNumber?: string;

    bookNumber?: string;

    standardNumber?: string;

    referenceBookNumber?: string;

    referenceEntryNumber?: string;

    contributors?: Array<models.AgentRole>;

    journalContributors?: Array<models.AgentRole>;

    reportContributors?: Array<models.AgentRole>;

    journalVolumeContributors?: Array<models.AgentRole>;

    journalIssueContributors?: Array<models.AgentRole>;

    journalArticleContributors?: Array<models.AgentRole>;

    monographContributors?: Array<models.AgentRole>;

    editedBookContributors?: Array<models.AgentRole>;

    bookSeriesContributors?: Array<models.AgentRole>;

    proceedingsArticleContributors?: Array<models.AgentRole>;

    bookSetContributors?: Array<models.AgentRole>;

    bookChapterContributors?: Array<models.AgentRole>;

    datasetContributors?: Array<models.AgentRole>;

    bookTrackContributors?: Array<models.AgentRole>;

    componentContributors?: Array<models.AgentRole>;

    dissertationContributors?: Array<models.AgentRole>;

    proceedingsContributors?: Array<models.AgentRole>;

    repotrSeriesContributors?: Array<models.AgentRole>;

    bookContributors?: Array<models.AgentRole>;

    referenceBookContributors?: Array<models.AgentRole>;

    referenceEntryContributors?: Array<models.AgentRole>;

    standardContributors?: Array<models.AgentRole>;

    standardSeriesContributors?: Array<models.AgentRole>;

    journalArticlePublicationYear?: string;

    monographPublicationYear?: string;

    reportPublicationYear?: string;

    editedBookPublicationYear?: string;

    dissertationPublicationYear?: string;

    proceedingsArticlePublicationYear?: string;

    datasetPublicationYear?: string;

    proceedingsPublicationYear?: string;

    bookPublicationYear?: string;

    referenceBookPublicationYear?: string;

    standardPublicationYear?: string;

    status?: string;

    parts?: Array<models.BibliographicEntry>;

    partOf?: string;

    cites?: Array<string>;

    monographEmbodiedAs?: Array<models.ResourceEmbodiment>;

    editedBookEmbodiedAs?: Array<models.ResourceEmbodiment>;

    bookSeriesEmbodiedAs?: Array<models.ResourceEmbodiment>;

    bookSetEmbodiedAs?: Array<models.ResourceEmbodiment>;

    bookPartEmbodiedAs?: Array<models.ResourceEmbodiment>;

    bookTrackEmbodiedAs?: Array<models.ResourceEmbodiment>;

    componentEmbodiedAs?: Array<models.ResourceEmbodiment>;

    dissertationEmbodiedAs?: Array<models.ResourceEmbodiment>;

    proceedingsArticleEmbodiedAs?: Array<models.ResourceEmbodiment>;

    proceedingsEmbodiedAs?: Array<models.ResourceEmbodiment>;

    journalEmbodiedAs?: Array<models.ResourceEmbodiment>;

    journalVolumeEmbodiedAs?: Array<models.ResourceEmbodiment>;

    journalIssueEmbodiedAs?: Array<models.ResourceEmbodiment>;

    journalArticleEmbodiedAs?: Array<models.ResourceEmbodiment>;

    datasetEmbodiedAs?: Array<models.ResourceEmbodiment>;

    reportEmbodiedAs?: Array<models.ResourceEmbodiment>;

    reportSeriesEmbodiedAs?: Array<models.ResourceEmbodiment>;

    bookEmbodiedAs?: Array<models.ResourceEmbodiment>;

    referenceBookEmbodiedAs?: Array<models.ResourceEmbodiment>;

    referenceEntryEmbodiedAs?: Array<models.ResourceEmbodiment>;

    standardEmbodiedAs?: Array<models.ResourceEmbodiment>;

    standardSeriesEmbodiedAs?: Array<models.ResourceEmbodiment>;

}
