/**
 * LOC-DB Central Component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * An entry returned by an RSS/ Atom/ RDF feed. A description of all the fields can be found here: https://www.npmjs.com/package/feedparser 
 */
export interface FeedEntry {
    title?: string;

    description?: string;

    summary?: string;

    link?: string;

    origlink?: string;

    permalink?: string;

    date?: string;

    pubdate?: string;

    author?: string;

    guid?: string;

    comments?: string;

    image?: models.FeedEntryImage;

    categories?: Array<string>;

    source?: models.FeedEntryImage;

    enclosures?: Array<models.FeedEntryEnclosures>;

    meta?: models.FeedEntryMeta;

}
