/**
 * LOC-DB Central Component
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ToDo {
    _id: string;

    identifiers?: Array<models.Identifier>;

    type?: string;

    title?: string;

    subtitle?: string;

    edition?: string;

    number?: number;

    contributors?: Array<models.AgentRole>;

    publicationYear?: string;

    children?: Array<models.ToDoParts>;

}
